#!/usr/bin/env python2
#-*- coding:utf-8 -*-

""" 取两个排序数组的中位数(取两个排序数组的第K位数)
"""

def get_middle_of_arrays(array_a,array_b):
	""" middle of arrays """
	
	def helper(k,array_a,array_b,p_as,p_ae,p_bs,p_be):
		len_a = (p_ae -p_as + 1)	
		len_b = (p_be -p_bs + 1)
		if len_a == 0:
			return array_b[k]
		if len_b == 0:
			return array_a[k]					
								
				
			
			
						
			
c = [1,2,4,7,9,11,14,16,20]
b = [2,4,6]
print get_middle_of_arrays(c,b)

